# Generated by Django 2.2.14 on 2021-11-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isbn', models.BigIntegerField()),
                ('bookname', models.TextField()),
                ('book_author', models.TextField()),
                ('book_publisher', models.TextField()),
                ('book_count', models.IntegerField()),
            ],
        ),
    ]
