# Generated by Django 2.2.12 on 2021-12-24 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'ordering': ['id']},
        ),
    ]
